-- Two separate things that arrived together: how a candidate gets into a live examination,
-- and how anybody changes their own password afterwards.
--
-- ------------------------------------------------------------------ exam access
--
-- Until now, being assigned to an examination was the whole of being allowed into it. That is
-- right for a contest and wrong for a paper sat in a room: the roster is fixed days in advance,
-- and the thing that has to be true at the moment somebody opens the paper is that they are
-- sitting in the room the invigilator is standing in. An assignment cannot express that. A
-- password handed out at the desk can.
--
-- Two passwords, because they answer different questions and a deployment asked for both:
--
--   * The examination password is one string for the whole paper, read out or written on the
--     board when the invigilator starts it. It says "this sitting has begun" — which is why it
--     cannot simply live in the assignment, and why rotating it has to end every session that
--     was opened with the old one.
--   * A candidate's own passcode is unique to that person for that paper, handed to them on
--     their desk. It says "the person typing this is the person this seat belongs to", which
--     the shared password cannot say on its own, since by definition everybody in the room
--     has it.
--
-- Neither is ever emailed. They are printed and carried into the room, which is the whole
-- point: the credential the candidate's own mailbox holds gets them into CPIntel, and getting
-- into the paper additionally needs something only the invigilator can give them.
--
-- STORED REVERSIBLY, WHICH IS A DECISION AND NOT AN OVERSIGHT. Everywhere else in this system
-- a secret is hashed, because nothing needs to read it back. Here the invigilator does: they
-- print the desk slips the morning of the paper, and they re-read a code for a candidate whose
-- slip went missing halfway through. A hash cannot do either, and an arrangement that forces a
-- regeneration every time somebody loses a piece of paper would be abandoned by the second
-- sitting. So these are encrypted with AES-256-GCM under a key that lives in the environment
-- (CPINTEL_EXAM_PASSWORD_KEY) rather than in this database — see ExamPasswordService — and a
-- dump of Postgres alone yields nothing. The bound on the damage is the same one the passwords
-- themselves have: they are worthless once the paper's window has closed.

ALTER TABLE group_contests
    -- AES-256-GCM, base64. Null means this examination has no shared password yet, and one
    -- with none does not ask for it — an admin who has not generated one has not decided to
    -- require one.
    ADD COLUMN exam_password          VARCHAR(500),
    ADD COLUMN exam_password_set_at   TIMESTAMPTZ,
    ADD COLUMN exam_password_set_by   BIGINT,
    -- Bumped on every rotation. An access grant records the generation it was issued under, so
    -- rotating a leaked password ends the sessions opened with it without touching anything
    -- else. Without this, rotation would be advice rather than an action.
    ADD COLUMN exam_password_gen      INTEGER DEFAULT 0 NOT NULL;

ALTER TABLE group_contests
    ADD CONSTRAINT fk_gc_password_by FOREIGN KEY (exam_password_set_by)
        REFERENCES users(user_id) ON DELETE SET NULL;

-- One candidate's own passcode for one examination.
--
-- Rows exist only for people who were issued one, which is deliberately not the same set as
-- the assignment list: an examination may be run on the shared password alone, and a candidate
-- added to the roster an hour before the paper needs a code generated for them rather than
-- inheriting a blank one that would let them in with nothing.
CREATE TABLE exam_passcodes (
    passcode_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contest_id    BIGINT      NOT NULL,
    user_id       BIGINT      NOT NULL,
    -- AES-256-GCM, base64. See the note above for why this is not a hash.
    code          VARCHAR(500) NOT NULL,
    issued_at     TIMESTAMPTZ DEFAULT now() NOT NULL,
    issued_by     BIGINT,
    -- When this code first opened the paper, and how many times it has been tried since. Both
    -- are for the invigilator: a code first used from an empty seat, or one that has opened the
    -- paper twice, is worth knowing about and is not something the software should rule on.
    first_used_at TIMESTAMPTZ,
    use_count     INTEGER     DEFAULT 0 NOT NULL,
    CONSTRAINT fk_ep_contest FOREIGN KEY (contest_id) REFERENCES group_contests(contest_id) ON DELETE CASCADE,
    CONSTRAINT fk_ep_user    FOREIGN KEY (user_id)    REFERENCES users(user_id)             ON DELETE CASCADE,
    CONSTRAINT fk_ep_issuer  FOREIGN KEY (issued_by)  REFERENCES users(user_id)             ON DELETE SET NULL,
    CONSTRAINT uq_ep_contest_user UNIQUE (contest_id, user_id)
);

CREATE INDEX idx_ep_contest ON exam_passcodes(contest_id);

-- ---------------------------------------------------------------- accounts
--
-- The first password is handed over with the username when the account is created, off the
-- back of a deployment rather than through a mailbox. After that it is the owner's, and the
-- owner needs a way to change it that does not involve asking an administrator — which is what
-- the reset mail is for. The column records when that last happened, so an admin reading an
-- account can tell a password that was chosen by its owner from one that is still the one they
-- were given.
ALTER TABLE users
    ADD COLUMN password_changed_at TIMESTAMPTZ;

-- Reset tokens are looked up by their hash on every attempt; without this each one is a scan
-- of a table nothing else indexes.
CREATE INDEX IF NOT EXISTS idx_vt_user_type ON verification_tokens(user_id, token_type);
