BEGIN EXECUTE IMMEDIATE 'ALTER TABLE roadmap_nodes ADD (node_key VARCHAR2(60))'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE roadmap_nodes ADD (min_difficulty NUMBER(5))'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE roadmap_nodes ADD (max_difficulty NUMBER(5))'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE roadmap_nodes ADD (prereq_keys VARCHAR2(500))'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX idx_rn_user_nodekey ON roadmap_nodes(user_id, node_key)'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
DELETE FROM roadmap_nodes WHERE node_key IS NULL;
COMMIT;
