-- Classrooms: one DOMjudge instance each, and the container for everything run on it.
--
-- Until now a deployment talked to exactly one DOMjudge, named in the environment. A student
-- taking two courses sits on two judges with two different team accounts, and nothing here
-- could say which judge a contest lived on or which login to submit with. A classroom is that
-- missing piece: it owns one judge, the people enrolled on it, the teams (groups) inside it
-- and the events run in it. Later assessment kinds that need no judge at all (quizzes) hang
-- off the classroom too, which is why the judge is a property of it rather than the other
-- way round.

CREATE TABLE classrooms (
    classroom_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                  VARCHAR(120)  NOT NULL,
    description           VARCHAR(500),
    -- The DOMjudge root, without /api. Nullable only for the classroom this migration builds
    -- from existing data, which an admin gives a judge afterwards; the API requires it.
    -- Unique because two classrooms on one judge would hold two logins for the same team.
    domjudge_url          VARCHAR(500),
    -- The optional contest-wide account (see DomjudgeClient). The password is AES-GCM under
    -- CPINTEL_DOMJUDGE_CREDENTIAL_KEY, the same key as the contestants' logins.
    service_username      VARCHAR(100),
    service_password      VARCHAR(500),
    owner_id              BIGINT,
    is_active             BOOLEAN       DEFAULT TRUE NOT NULL,
    created_at            TIMESTAMPTZ   DEFAULT now() NOT NULL,
    updated_at            TIMESTAMPTZ,
    CONSTRAINT fk_cr_owner FOREIGN KEY (owner_id) REFERENCES users(user_id) ON DELETE SET NULL
);

CREATE UNIQUE INDEX uq_cr_domjudge_url ON classrooms (lower(domjudge_url))
    WHERE domjudge_url IS NOT NULL;

-- Who is enrolled. The judge login itself stays in Redis (DomjudgeCredentialStore); this is
-- the half that is not a secret, so an admin can see who is linked where without anything
-- being decrypted, and so enrolment survives a login expiring.
CREATE TABLE classroom_members (
    classroom_member_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    classroom_id          BIGINT       NOT NULL,
    user_id               BIGINT       NOT NULL,
    domjudge_username     VARCHAR(100),
    joined_at             TIMESTAMPTZ  DEFAULT now() NOT NULL,
    CONSTRAINT fk_cm_classroom FOREIGN KEY (classroom_id) REFERENCES classrooms(classroom_id) ON DELETE CASCADE,
    CONSTRAINT fk_cm_user      FOREIGN KEY (user_id)      REFERENCES users(user_id)           ON DELETE CASCADE,
    CONSTRAINT uq_cm_classroom_user UNIQUE (classroom_id, user_id)
);

CREATE INDEX idx_cm_user ON classroom_members (user_id);

-- Admins who run a classroom besides its owner. Superadmins see every classroom regardless.
CREATE TABLE classroom_staff (
    classroom_id          BIGINT       NOT NULL,
    user_id               BIGINT       NOT NULL,
    added_at              TIMESTAMPTZ  DEFAULT now() NOT NULL,
    PRIMARY KEY (classroom_id, user_id),
    CONSTRAINT fk_cs_classroom FOREIGN KEY (classroom_id) REFERENCES classrooms(classroom_id) ON DELETE CASCADE,
    CONSTRAINT fk_cs_user      FOREIGN KEY (user_id)      REFERENCES users(user_id)           ON DELETE CASCADE
);

ALTER TABLE contest_groups ADD COLUMN classroom_id BIGINT;
ALTER TABLE group_contests ADD COLUMN classroom_id BIGINT;

-- Everything that already exists came from the one judge the deployment used, so it all moves
-- into one classroom built from the data itself. It starts without a judge; an admin sets its
-- DOMjudge URL from the console. ClassroomBootstrap moves the Redis logins and Mongo rows in.
INSERT INTO classrooms (name, description)
SELECT 'Default classroom', 'Created when this deployment moved to classrooms.'
WHERE EXISTS (SELECT 1 FROM contest_groups) OR EXISTS (SELECT 1 FROM group_contests);

UPDATE contest_groups SET classroom_id = (SELECT min(classroom_id) FROM classrooms);
UPDATE group_contests SET classroom_id = (SELECT min(classroom_id) FROM classrooms);

-- A DOMjudge contest id is only unique on its own judge: two instances both have a contest
-- called "demo". So CPIntel names a DOMjudge contest by classroom and id together,
-- "<classroom>~<contest>", everywhere it stores or routes one - here, in the Mongo archive
-- and file rules, and in the compete URLs. Every lookup keyed on (platform, external_id)
-- therefore stays unique without each one having to learn about classrooms. See
-- JudgeContestRef. '~' is outside DOMjudge's own id alphabet, so the split is unambiguous.
UPDATE group_contests
   SET external_id = classroom_id || '~' || external_id
 WHERE platform = 'DOMJUDGE' AND position('~' in external_id) = 0;

INSERT INTO classroom_members (classroom_id, user_id, domjudge_username)
SELECT DISTINCT g.classroom_id, m.user_id, NULL
  FROM group_members m JOIN contest_groups g ON g.group_id = m.group_id
ON CONFLICT DO NOTHING;

INSERT INTO classroom_members (classroom_id, user_id, domjudge_username)
SELECT DISTINCT c.classroom_id, a.user_id, NULL
  FROM contest_assignments a JOIN group_contests c ON c.contest_id = a.contest_id
 WHERE a.user_id IS NOT NULL
ON CONFLICT DO NOTHING;

ALTER TABLE contest_groups
    ALTER COLUMN classroom_id SET NOT NULL,
    ADD CONSTRAINT fk_cg_classroom FOREIGN KEY (classroom_id)
        REFERENCES classrooms(classroom_id) ON DELETE RESTRICT;

ALTER TABLE group_contests
    ALTER COLUMN classroom_id SET NOT NULL,
    ADD CONSTRAINT fk_gc_classroom FOREIGN KEY (classroom_id)
        REFERENCES classrooms(classroom_id) ON DELETE RESTRICT,
    -- The qualified id and the column must agree, or an event would route to one judge and
    -- be listed under another classroom.
    ADD CONSTRAINT chk_gc_domjudge_ref CHECK (
        platform <> 'DOMJUDGE' OR external_id LIKE classroom_id || '~%');

CREATE INDEX idx_cg_classroom ON contest_groups (classroom_id);
CREATE INDEX idx_gc_classroom ON group_contests (classroom_id, kind);
