-- CPIntel core schema (PostgreSQL).
--
-- This is a collapsed baseline. The Oracle history (V1-V20) had nine migrations that
-- existed only to bolt on audit columns or patch a PL/SQL formula; none of that history
-- is reproducible on Postgres and none of it was worth carrying, so the final Oracle
-- schema state is expressed here directly.
--
-- Type mapping from the Oracle original:
--   NUMBER GENERATED BY DEFAULT AS IDENTITY -> BIGINT GENERATED BY DEFAULT AS IDENTITY
--   VARCHAR2(n)                             -> VARCHAR(n)
--   NUMBER(1) + CHECK (col IN (0,1))        -> BOOLEAN   (every entity already maps Boolean)
--   NUMBER(5,2)                             -> NUMERIC(5,2)
--   CLOB                                    -> TEXT
--   TIMESTAMP DEFAULT SYSTIMESTAMP          -> TIMESTAMPTZ DEFAULT now()

-- Users
CREATE TABLE users (
    user_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(50)  NOT NULL UNIQUE,
    email         VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    full_name     VARCHAR(100),
    avatar_url    VARCHAR(500),
    country       VARCHAR(100),
    institution   VARCHAR(200),
    role          VARCHAR(20)  DEFAULT 'USER' NOT NULL,
    is_active     BOOLEAN      DEFAULT TRUE  NOT NULL,
    is_verified   BOOLEAN      DEFAULT FALSE NOT NULL,
    created_at    TIMESTAMPTZ  DEFAULT now() NOT NULL,
    updated_at    TIMESTAMPTZ  DEFAULT now() NOT NULL,
    CONSTRAINT chk_role CHECK (role IN ('USER','ADMIN'))
);

-- Platform linked accounts
CREATE TABLE platform_accounts (
    account_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT       NOT NULL,
    platform       VARCHAR(20)  NOT NULL,
    handle         VARCHAR(100) NOT NULL,
    current_rating INTEGER,
    max_rating     INTEGER,
    last_synced_at TIMESTAMPTZ,
    sync_status    VARCHAR(20)  DEFAULT 'PENDING',
    is_active      BOOLEAN      DEFAULT TRUE,
    created_at     TIMESTAMPTZ  DEFAULT now() NOT NULL,
    updated_at     TIMESTAMPTZ,
    CONSTRAINT fk_pa_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    CONSTRAINT uq_pa_user_platform UNIQUE (user_id, platform),
    CONSTRAINT chk_platform CHECK (platform IN ('CODEFORCES','LEETCODE','CODECHEF')),
    CONSTRAINT chk_sync_status CHECK (sync_status IN ('PENDING','RUNNING','COMPLETED','FAILED'))
);

-- Contest summaries (aggregated from MongoDB raw data)
CREATE TABLE contest_summaries (
    contest_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT       NOT NULL,
    platform          VARCHAR(20)  NOT NULL,
    contest_name      VARCHAR(200),
    contest_cf_id     VARCHAR(100),
    rank              INTEGER,
    rating_before     INTEGER,
    rating_after      INTEGER,
    rating_change     INTEGER,
    problems_solved   INTEGER      DEFAULT 0,
    total_problems    INTEGER      DEFAULT 0,
    first_solve_mins  INTEGER,
    avg_solve_mins    INTEGER,
    wrong_submissions INTEGER      DEFAULT 0,
    penalty_mins      INTEGER      DEFAULT 0,
    contest_date      TIMESTAMPTZ,
    created_at        TIMESTAMPTZ  DEFAULT now() NOT NULL,
    updated_at        TIMESTAMPTZ,
    CONSTRAINT fk_cs_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

-- Topic mastery
CREATE TABLE topic_mastery (
    mastery_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id            BIGINT       NOT NULL,
    topic              VARCHAR(100) NOT NULL,
    mastery_score      NUMERIC(5,2) DEFAULT 0,
    confidence_score   NUMERIC(5,2) DEFAULT 0,
    revision_score     NUMERIC(5,2) DEFAULT 0,
    decay_score        NUMERIC(5,2) DEFAULT 0,
    problems_solved    INTEGER      DEFAULT 0,
    problems_attempted INTEGER      DEFAULT 0,
    last_practiced_at  TIMESTAMPTZ,
    computed_at        TIMESTAMPTZ  DEFAULT now(),
    CONSTRAINT fk_tm_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    CONSTRAINT uq_tm_user_topic UNIQUE (user_id, topic),
    CONSTRAINT chk_mastery_range CHECK (mastery_score BETWEEN 0 AND 100),
    CONSTRAINT chk_confidence_range CHECK (confidence_score BETWEEN 0 AND 100)
);

-- Recommendations
CREATE TABLE recommendations (
    rec_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT      NOT NULL,
    rec_type     VARCHAR(20) NOT NULL,
    problem_list TEXT,
    metadata     TEXT,
    generated_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    expires_at   TIMESTAMPTZ,
    is_consumed  BOOLEAN     DEFAULT FALSE,
    created_at   TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at   TIMESTAMPTZ,
    CONSTRAINT fk_rec_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    CONSTRAINT chk_rec_type CHECK (rec_type IN ('DAILY','WEEKLY','REVISION','CONTEST_PREP'))
);

-- Revision schedule
CREATE TABLE revision_schedule (
    revision_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT       NOT NULL,
    topic             VARCHAR(100) NOT NULL,
    next_revision_at  TIMESTAMPTZ  NOT NULL,
    revision_priority INTEGER      DEFAULT 50,
    decay_score       NUMERIC(5,2) DEFAULT 0,
    interval_days     INTEGER      DEFAULT 1,
    repetition_count  INTEGER      DEFAULT 0,
    ease_factor       NUMERIC(5,2) DEFAULT 2.5,
    last_revised_at   TIMESTAMPTZ,
    created_at        TIMESTAMPTZ  DEFAULT now() NOT NULL,
    updated_at        TIMESTAMPTZ,
    CONSTRAINT fk_rs_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    CONSTRAINT uq_rs_user_topic UNIQUE (user_id, topic)
);

-- Roadmap nodes (node_key/difficulty/prereqs came from the V15 taxonomy upgrade)
CREATE TABLE roadmap_nodes (
    node_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT       NOT NULL,
    topic          VARCHAR(100) NOT NULL,
    parent_topic   VARCHAR(100),
    status         VARCHAR(20)  DEFAULT 'LOCKED',
    order_index    INTEGER      DEFAULT 0,
    node_key       VARCHAR(60),
    min_difficulty INTEGER,
    max_difficulty INTEGER,
    prereq_keys    VARCHAR(500),
    unlocked_at    TIMESTAMPTZ,
    completed_at   TIMESTAMPTZ,
    created_at     TIMESTAMPTZ  DEFAULT now() NOT NULL,
    updated_at     TIMESTAMPTZ,
    CONSTRAINT fk_rn_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    CONSTRAINT chk_rn_status CHECK (status IN ('LOCKED','UNLOCKED','IN_PROGRESS','COMPLETED'))
);

-- Unified scores
CREATE TABLE unified_scores (
    score_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT       NOT NULL UNIQUE,
    cf_score      NUMERIC(7,2) DEFAULT 0,
    lc_score      NUMERIC(7,2) DEFAULT 0,
    cc_score      NUMERIC(7,2) DEFAULT 0,
    unified_score NUMERIC(7,2) DEFAULT 0,
    cf_weight     NUMERIC(4,2) DEFAULT 0.40,
    lc_weight     NUMERIC(4,2) DEFAULT 0.35,
    cc_weight     NUMERIC(4,2) DEFAULT 0.25,
    computed_at   TIMESTAMPTZ  DEFAULT now(),
    CONSTRAINT fk_us_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

-- Refresh tokens
CREATE TABLE refresh_tokens (
    token_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT       NOT NULL,
    token       VARCHAR(500) NOT NULL UNIQUE,
    device_info VARCHAR(500),
    ip_address  VARCHAR(45),
    expires_at  TIMESTAMPTZ  NOT NULL,
    revoked     BOOLEAN      DEFAULT FALSE NOT NULL,
    created_at  TIMESTAMPTZ  DEFAULT now() NOT NULL,
    CONSTRAINT fk_rt_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

-- Email verification / password reset tokens
CREATE TABLE verification_tokens (
    token_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL,
    token      VARCHAR(200) NOT NULL UNIQUE,
    token_type VARCHAR(30)  NOT NULL,
    expires_at TIMESTAMPTZ  NOT NULL,
    used       BOOLEAN      DEFAULT FALSE NOT NULL,
    created_at TIMESTAMPTZ  DEFAULT now() NOT NULL,
    CONSTRAINT fk_vt_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    CONSTRAINT chk_vt_type CHECK (token_type IN ('EMAIL_VERIFY','PASSWORD_RESET'))
);

-- Background sync job tracking
CREATE TABLE sync_jobs (
    job_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT       NOT NULL,
    platform     VARCHAR(20)  NOT NULL,
    job_type     VARCHAR(30)  DEFAULT 'INCREMENTAL',
    status       VARCHAR(20)  DEFAULT 'QUEUED',
    progress_pct NUMERIC(5,2) DEFAULT 0,
    items_synced INTEGER      DEFAULT 0,
    error_msg    VARCHAR(1000),
    started_at   TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    created_at   TIMESTAMPTZ  DEFAULT now() NOT NULL,
    updated_at   TIMESTAMPTZ,
    CONSTRAINT fk_sj_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    CONSTRAINT chk_sj_status CHECK (status IN ('QUEUED','RUNNING','COMPLETED','FAILED','CANCELLED'))
);

-- Audit log
CREATE TABLE audit_log (
    log_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT,
    action      VARCHAR(100) NOT NULL,
    entity_type VARCHAR(50),
    entity_id   VARCHAR(100),
    ip_address  VARCHAR(45),
    user_agent  VARCHAR(500),
    created_at  TIMESTAMPTZ DEFAULT now() NOT NULL
);
