-- Users
CREATE TABLE users (
    user_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR2(50)  NOT NULL UNIQUE,
    email         VARCHAR2(255) NOT NULL UNIQUE,
    password_hash VARCHAR2(255) NOT NULL,
    full_name     VARCHAR2(100),
    avatar_url    VARCHAR2(500),
    country       VARCHAR2(100),
    institution   VARCHAR2(200),
    role          VARCHAR2(20)  DEFAULT 'USER' NOT NULL,
    is_active     NUMBER(1)     DEFAULT 1 NOT NULL,
    is_verified   NUMBER(1)     DEFAULT 0 NOT NULL,
    created_at    TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at    TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT chk_role CHECK (role IN ('USER','ADMIN')),
    CONSTRAINT chk_active CHECK (is_active IN (0,1)),
    CONSTRAINT chk_verified CHECK (is_verified IN (0,1))
);

-- Platform linked accounts
CREATE TABLE platform_accounts (
    account_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           NUMBER        NOT NULL,
    platform          VARCHAR2(20)  NOT NULL,
    handle            VARCHAR2(100) NOT NULL,
    current_rating    NUMBER(6),
    max_rating        NUMBER(6),
    last_synced_at    TIMESTAMP,
    sync_status       VARCHAR2(20)  DEFAULT 'PENDING',
    is_active         NUMBER(1)     DEFAULT 1,
    created_at        TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_pa_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    CONSTRAINT uq_pa_user_platform UNIQUE (user_id, platform),
    CONSTRAINT chk_platform CHECK (platform IN ('CODEFORCES','LEETCODE','CODECHEF')),
    CONSTRAINT chk_sync_status CHECK (sync_status IN ('PENDING','RUNNING','COMPLETED','FAILED'))
);

-- Contest summaries (aggregated from MongoDB raw data)
CREATE TABLE contest_summaries (
    contest_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           NUMBER        NOT NULL,
    platform          VARCHAR2(20)  NOT NULL,
    contest_name      VARCHAR2(200),
    contest_cf_id     VARCHAR2(100),
    rank              NUMBER(8),
    rating_before     NUMBER(6),
    rating_after      NUMBER(6),
    rating_change     NUMBER(6),
    problems_solved   NUMBER(3)     DEFAULT 0,
    total_problems    NUMBER(3)     DEFAULT 0,
    first_solve_mins  NUMBER(6),
    avg_solve_mins    NUMBER(6),
    wrong_submissions NUMBER(5)     DEFAULT 0,
    penalty_mins      NUMBER(8)     DEFAULT 0,
    contest_date      TIMESTAMP,
    created_at        TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_cs_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

-- Topic mastery
CREATE TABLE topic_mastery (
    mastery_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           NUMBER        NOT NULL,
    topic             VARCHAR2(100) NOT NULL,
    mastery_score     NUMBER(5,2)   DEFAULT 0,
    confidence_score  NUMBER(5,2)   DEFAULT 0,
    revision_score    NUMBER(5,2)   DEFAULT 0,
    decay_score       NUMBER(5,2)   DEFAULT 0,
    problems_solved   NUMBER(6)     DEFAULT 0,
    problems_attempted NUMBER(6)    DEFAULT 0,
    last_practiced_at TIMESTAMP,
    computed_at       TIMESTAMP     DEFAULT SYSTIMESTAMP,
    CONSTRAINT fk_tm_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    CONSTRAINT uq_tm_user_topic UNIQUE (user_id, topic),
    CONSTRAINT chk_mastery_range CHECK (mastery_score BETWEEN 0 AND 100),
    CONSTRAINT chk_confidence_range CHECK (confidence_score BETWEEN 0 AND 100)
);

-- Recommendations
CREATE TABLE recommendations (
    rec_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         NUMBER        NOT NULL,
    rec_type        VARCHAR2(20)  NOT NULL,
    problem_list    CLOB,
    metadata        CLOB,
    generated_at    TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    expires_at      TIMESTAMP,
    is_consumed     NUMBER(1)     DEFAULT 0,
    CONSTRAINT fk_rec_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    CONSTRAINT chk_rec_type CHECK (rec_type IN ('DAILY','WEEKLY','REVISION','CONTEST_PREP'))
);

-- Revision schedule
CREATE TABLE revision_schedule (
    revision_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           NUMBER        NOT NULL,
    topic             VARCHAR2(100) NOT NULL,
    next_revision_at  TIMESTAMP     NOT NULL,
    revision_priority NUMBER(3)     DEFAULT 50,
    decay_score       NUMBER(5,2)   DEFAULT 0,
    interval_days     NUMBER(5)     DEFAULT 1,
    repetition_count  NUMBER(5)     DEFAULT 0,
    ease_factor       NUMBER(5,2)   DEFAULT 2.5,
    last_revised_at   TIMESTAMP,
    created_at        TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_rs_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    CONSTRAINT uq_rs_user_topic UNIQUE (user_id, topic)
);

-- Roadmap nodes
CREATE TABLE roadmap_nodes (
    node_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       NUMBER        NOT NULL,
    topic         VARCHAR2(100) NOT NULL,
    parent_topic  VARCHAR2(100),
    status        VARCHAR2(20)  DEFAULT 'LOCKED',
    order_index   NUMBER(5)     DEFAULT 0,
    unlocked_at   TIMESTAMP,
    completed_at  TIMESTAMP,
    created_at    TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_rn_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    CONSTRAINT chk_rn_status CHECK (status IN ('LOCKED','UNLOCKED','IN_PROGRESS','COMPLETED'))
);

-- Unified scores
CREATE TABLE unified_scores (
    score_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           NUMBER        NOT NULL UNIQUE,
    cf_score          NUMBER(7,2)   DEFAULT 0,
    lc_score          NUMBER(7,2)   DEFAULT 0,
    cc_score          NUMBER(7,2)   DEFAULT 0,
    unified_score     NUMBER(7,2)   DEFAULT 0,
    cf_weight         NUMBER(4,2)   DEFAULT 0.40,
    lc_weight         NUMBER(4,2)   DEFAULT 0.35,
    cc_weight         NUMBER(4,2)   DEFAULT 0.25,
    computed_at       TIMESTAMP     DEFAULT SYSTIMESTAMP,
    CONSTRAINT fk_us_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

-- Audit log
CREATE TABLE audit_log (
    log_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     NUMBER,
    action      VARCHAR2(100) NOT NULL,
    entity_type VARCHAR2(50),
    entity_id   VARCHAR2(100),
    ip_address  VARCHAR2(45),
    user_agent  VARCHAR2(500),
    created_at  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);
