-- A TA freezing their marking, and an admin sending answers back to them.
--
-- Once a TA has finished, they freeze their marking on the examination and can no longer change
-- it. An admin can still change any mark themselves, and can reopen single answers for the TA
-- to look at again. The TA can change only those, and freezing again closes them.

CREATE TABLE exam_ta_freezes (
    contest_id  BIGINT       NOT NULL,
    ta_user_id  BIGINT       NOT NULL,
    frozen_at   TIMESTAMPTZ  DEFAULT now() NOT NULL,
    PRIMARY KEY (contest_id, ta_user_id),
    CONSTRAINT fk_etf_contest FOREIGN KEY (contest_id) REFERENCES group_contests(contest_id) ON DELETE CASCADE,
    CONSTRAINT fk_etf_ta      FOREIGN KEY (ta_user_id) REFERENCES users(user_id)             ON DELETE CASCADE
);

-- One answer (student and question) an admin reopened for re-marking.
CREATE TABLE exam_mark_reopens (
    contest_id    BIGINT       NOT NULL,
    user_id       BIGINT       NOT NULL,
    problem_label VARCHAR(16)  NOT NULL,
    reopened_by   BIGINT,
    reopened_at   TIMESTAMPTZ  DEFAULT now() NOT NULL,
    PRIMARY KEY (contest_id, user_id, problem_label),
    CONSTRAINT fk_emr_contest FOREIGN KEY (contest_id)  REFERENCES group_contests(contest_id) ON DELETE CASCADE,
    CONSTRAINT fk_emr_user    FOREIGN KEY (user_id)     REFERENCES users(user_id)             ON DELETE CASCADE,
    CONSTRAINT fk_emr_by      FOREIGN KEY (reopened_by) REFERENCES users(user_id)             ON DELETE SET NULL
);

-- Every answer that needed work after a TA froze: sent back to them (REOPENED), or changed by
-- an admin over their mark (ADMIN_CHANGED). Kept as history, so the admin's dashboard can say
-- how many changes each TA's marking needed even after the TA freezes again.
CREATE TABLE exam_eval_changes (
    change_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contest_id    BIGINT       NOT NULL,
    ta_user_id    BIGINT       NOT NULL,
    user_id       BIGINT       NOT NULL,
    problem_label VARCHAR(16)  NOT NULL,
    kind          VARCHAR(16)  NOT NULL,
    changed_by    BIGINT,
    changed_at    TIMESTAMPTZ  DEFAULT now() NOT NULL,
    CONSTRAINT fk_eec_contest FOREIGN KEY (contest_id) REFERENCES group_contests(contest_id) ON DELETE CASCADE,
    CONSTRAINT fk_eec_ta      FOREIGN KEY (ta_user_id) REFERENCES users(user_id)             ON DELETE CASCADE,
    CONSTRAINT fk_eec_user    FOREIGN KEY (user_id)    REFERENCES users(user_id)             ON DELETE CASCADE,
    CONSTRAINT fk_eec_by      FOREIGN KEY (changed_by) REFERENCES users(user_id)             ON DELETE SET NULL,
    CONSTRAINT chk_eec_kind CHECK (kind IN ('REOPENED', 'ADMIN_CHANGED'))
);

CREATE INDEX idx_eec_contest ON exam_eval_changes (contest_id, ta_user_id);
