-- Refresh tokens
CREATE TABLE refresh_tokens (
    token_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     NUMBER        NOT NULL,
    token       VARCHAR2(500) NOT NULL UNIQUE,
    device_info VARCHAR2(500),
    ip_address  VARCHAR2(45),
    expires_at  TIMESTAMP     NOT NULL,
    revoked     NUMBER(1)     DEFAULT 0 NOT NULL,
    created_at  TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_rt_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

-- Email verification tokens
CREATE TABLE verification_tokens (
    token_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     NUMBER        NOT NULL,
    token       VARCHAR2(200) NOT NULL UNIQUE,
    token_type  VARCHAR2(30)  NOT NULL,
    expires_at  TIMESTAMP     NOT NULL,
    used        NUMBER(1)     DEFAULT 0 NOT NULL,
    created_at  TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_vt_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    CONSTRAINT chk_vt_type CHECK (token_type IN ('EMAIL_VERIFY','PASSWORD_RESET'))
);

-- Sync jobs table for tracking background sync status
CREATE TABLE sync_jobs (
    job_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       NUMBER        NOT NULL,
    platform      VARCHAR2(20)  NOT NULL,
    job_type      VARCHAR2(30)  DEFAULT 'INCREMENTAL',
    status        VARCHAR2(20)  DEFAULT 'QUEUED',
    progress_pct  NUMBER(5,2)   DEFAULT 0,
    items_synced  NUMBER(8)     DEFAULT 0,
    error_msg     VARCHAR2(1000),
    started_at    TIMESTAMP,
    completed_at  TIMESTAMP,
    created_at    TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_sj_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    CONSTRAINT chk_sj_status CHECK (status IN ('QUEUED','RUNNING','COMPLETED','FAILED','CANCELLED'))
);
