-- Admin-hosted group contests.
--
-- CPIntel does not run the contest. Codeforces or DOMjudge does, with its own participants,
-- its own clock and its own scoreboard. What is modelled here is a group laid over that
-- contest: a named subset of CPIntel users whose results are extracted from the external
-- board and ranked against each other, plus whatever the desktop lock reported about how they
-- sat it.
--
-- Two consequences run through the whole schema. The external contest is identified by an
-- opaque string rather than a number, because a Codeforces contest id and a DOMjudge contest
-- id have nothing in common. And standings are stored as a cached snapshot rather than
-- computed on read, because building them costs one rate-limited API call per member.

CREATE TABLE contest_groups (
    group_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(120) NOT NULL,
    description VARCHAR(500),
    owner_id    BIGINT       NOT NULL,
    is_active   BOOLEAN      DEFAULT TRUE NOT NULL,
    created_at  TIMESTAMPTZ  DEFAULT now() NOT NULL,
    updated_at  TIMESTAMPTZ,
    -- The owner is kept even if deactivated: a group whose owner row vanished would leave
    -- contests and results with nobody accountable for them.
    CONSTRAINT fk_cg_owner FOREIGN KEY (owner_id) REFERENCES users(user_id)
);

CREATE TABLE group_members (
    member_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id        BIGINT       NOT NULL,
    user_id         BIGINT       NOT NULL,
    -- How this person appears on the external judge when it cannot be derived. Codeforces
    -- handles come from the linked platform account; DOMjudge has no such link, so the team
    -- name is recorded here or the member simply will not be found on the board.
    external_handle VARCHAR(100),
    joined_at       TIMESTAMPTZ  DEFAULT now() NOT NULL,
    CONSTRAINT fk_gm_group FOREIGN KEY (group_id) REFERENCES contest_groups(group_id) ON DELETE CASCADE,
    CONSTRAINT fk_gm_user  FOREIGN KEY (user_id)  REFERENCES users(user_id) ON DELETE CASCADE,
    CONSTRAINT uq_gm_group_user UNIQUE (group_id, user_id)
);

CREATE TABLE group_contests (
    contest_id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id               BIGINT       NOT NULL,
    platform               VARCHAR(20)  NOT NULL,
    -- A Codeforces contest id, or a DOMjudge contest id. Opaque on purpose.
    external_id            VARCHAR(100) NOT NULL,
    name                   VARCHAR(200) NOT NULL,
    url                    VARCHAR(500),
    starts_at              TIMESTAMPTZ,
    ends_at                TIMESTAMPTZ,
    -- Whether the desktop lock must be held to sit this one. Off means the round is casual and
    -- violations are not worth reporting.
    lockdown_required      BOOLEAN      DEFAULT TRUE NOT NULL,
    standings_refreshed_at TIMESTAMPTZ,
    standings_error        VARCHAR(500),
    created_at             TIMESTAMPTZ  DEFAULT now() NOT NULL,
    updated_at             TIMESTAMPTZ,
    CONSTRAINT fk_gc_group FOREIGN KEY (group_id) REFERENCES contest_groups(group_id) ON DELETE CASCADE,
    CONSTRAINT chk_gc_platform CHECK (platform IN ('CODEFORCES','DOMJUDGE')),
    -- The same external contest twice in one group would produce two competing snapshots of
    -- the same board.
    CONSTRAINT uq_gc_group_external UNIQUE (group_id, platform, external_id)
);

-- A cached snapshot of where each member stands, rebuilt on refresh rather than on read.
CREATE TABLE group_standings (
    row_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contest_id  BIGINT       NOT NULL,
    user_id     BIGINT       NOT NULL,
    handle      VARCHAR(100),
    -- Rank within the group, which is the whole point: a member who is 400th overall may be
    -- 3rd among the people they are actually being measured against.
    group_rank  INTEGER,
    solved      INTEGER      DEFAULT 0 NOT NULL,
    penalty     INTEGER      DEFAULT 0 NOT NULL,
    score       NUMERIC(10,2),
    -- Per-problem detail as JSON, so the board can show which problems fell without another
    -- table whose shape differs per judge.
    detail      TEXT,
    -- False when the member could not be found on the external board at all, which is normal
    -- before their first submission and a real problem afterwards.
    found       BOOLEAN      DEFAULT FALSE NOT NULL,
    computed_at TIMESTAMPTZ  DEFAULT now() NOT NULL,
    CONSTRAINT fk_gs_contest FOREIGN KEY (contest_id) REFERENCES group_contests(contest_id) ON DELETE CASCADE,
    CONSTRAINT fk_gs_user    FOREIGN KEY (user_id)    REFERENCES users(user_id) ON DELETE CASCADE,
    CONSTRAINT uq_gs_contest_user UNIQUE (contest_id, user_id)
);

-- What the desktop lock reported. Append-only, like the audit log it sits beside.
CREATE TABLE contest_violations (
    violation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contest_id   BIGINT       NOT NULL,
    user_id      BIGINT       NOT NULL,
    -- Generated by the client. The desktop app retries a failed report, and without this a
    -- flaky connection would turn one focus loss into five.
    event_id     VARCHAR(64)  NOT NULL,
    type         VARCHAR(40)  NOT NULL,
    detail       VARCHAR(500),
    duration_ms  BIGINT,
    occurred_at  TIMESTAMPTZ  NOT NULL,
    reported_at  TIMESTAMPTZ  DEFAULT now() NOT NULL,
    CONSTRAINT fk_cv_contest FOREIGN KEY (contest_id) REFERENCES group_contests(contest_id) ON DELETE CASCADE,
    CONSTRAINT fk_cv_user    FOREIGN KEY (user_id)    REFERENCES users(user_id) ON DELETE CASCADE,
    CONSTRAINT uq_cv_event UNIQUE (contest_id, user_id, event_id)
);

CREATE INDEX IF NOT EXISTS idx_gm_user        ON group_members(user_id);
CREATE INDEX IF NOT EXISTS idx_gc_group       ON group_contests(group_id);
CREATE INDEX IF NOT EXISTS idx_gc_window      ON group_contests(starts_at, ends_at);
CREATE INDEX IF NOT EXISTS idx_gs_contest     ON group_standings(contest_id, group_rank);
CREATE INDEX IF NOT EXISTS idx_cv_contest     ON contest_violations(contest_id, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_cv_user        ON contest_violations(user_id, occurred_at DESC);
