-- Contests and examinations as one kind of thing, with a lifecycle and an assignment list.
--
-- Until now a row in group_contests meant exactly one arrangement: a team, with an external
-- contest laid over it. Two requirements do not fit inside that shape.
--
--   * An examination is assigned to teams *and* to individual people, and an examination for
--     four named candidates has no team behind it at all. Hence contest_assignments, and hence
--     group_id becoming nullable: the team is now one way of naming participants rather than
--     the only way.
--
--   * An event has a life before and after its clock — configured but not yet visible (DRAFT),
--     and kept for the record once nobody may enter it again (ARCHIVED). Neither can be derived
--     from start and end times, so the lifecycle is stored. The two states in the middle still
--     are derived, because a stored "ACTIVE" is wrong for exactly as long as whatever updates
--     it is down, which is during the event.
--
-- The kind column is what separates the two products sharing this table. An examination carries
-- monitoring, an away-time threshold and a desktop policy; a contest may be public and usually
-- carries none of that. Keeping them in one table keeps standings, violations and the whole
-- compete arena working for both without a second copy of any of it.

ALTER TABLE group_contests
    ADD COLUMN kind                   VARCHAR(10)  DEFAULT 'CONTEST'   NOT NULL,
    ADD COLUMN lifecycle              VARCHAR(12)  DEFAULT 'SCHEDULED' NOT NULL,
    ADD COLUMN description            VARCHAR(2000),
    ADD COLUMN rules                  VARCHAR(4000),
    ADD COLUMN visibility             VARCHAR(10)  DEFAULT 'TEAMS'     NOT NULL,
    -- How long someone may be away from the examination window before it is worth telling them
    -- and recording it. Per event, because a two-hour written exam and a five-hour team contest
    -- do not mean the same thing by "away".
    ADD COLUMN away_threshold_seconds INTEGER      DEFAULT 10          NOT NULL,
    -- The desktop restrictions this event asks the locked-down client to apply, as JSON. Stored
    -- as a document rather than as columns because it is a policy handed to a client, and every
    -- new restriction would otherwise be a migration on a hot table.
    ADD COLUMN desktop_policy         TEXT,
    ADD COLUMN allowed_languages      VARCHAR(500),
    ADD COLUMN archived_at            TIMESTAMPTZ;

-- An examination for named individuals belongs to no team.
ALTER TABLE group_contests ALTER COLUMN group_id DROP NOT NULL;

ALTER TABLE group_contests
    ADD CONSTRAINT chk_gc_kind CHECK (kind IN ('CONTEST', 'EXAM')),
    ADD CONSTRAINT chk_gc_lifecycle
        CHECK (lifecycle IN ('DRAFT', 'SCHEDULED', 'ACTIVE', 'ENDED', 'ARCHIVED')),
    ADD CONSTRAINT chk_gc_visibility CHECK (visibility IN ('PUBLIC', 'TEAMS', 'USERS')),
    ADD CONSTRAINT chk_gc_away_threshold
        CHECK (away_threshold_seconds BETWEEN 1 AND 3600);

-- Everything that already exists is a contest that was laid over a team, and its lifecycle is
-- whatever its clock says. Rows with no window at all read as scheduled: they have not been
-- given a time yet, which is the one thing a missing window can honestly mean.
UPDATE group_contests
   SET lifecycle = CASE
        WHEN ends_at   IS NOT NULL AND ends_at   <  now() THEN 'ENDED'
        WHEN starts_at IS NOT NULL AND starts_at <= now() THEN 'ACTIVE'
        ELSE 'SCHEDULED'
       END;

-- Who may enter. One row per team or per person, never both: a mixed row would have two
-- meanings and no way to say which one an admin removed.
CREATE TABLE contest_assignments (
    assignment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contest_id    BIGINT      NOT NULL,
    group_id      BIGINT,
    user_id       BIGINT,
    assigned_by   BIGINT,
    assigned_at   TIMESTAMPTZ DEFAULT now() NOT NULL,
    CONSTRAINT fk_ca_contest FOREIGN KEY (contest_id) REFERENCES group_contests(contest_id) ON DELETE CASCADE,
    CONSTRAINT fk_ca_group   FOREIGN KEY (group_id)   REFERENCES contest_groups(group_id)   ON DELETE CASCADE,
    CONSTRAINT fk_ca_user    FOREIGN KEY (user_id)    REFERENCES users(user_id)             ON DELETE CASCADE,
    CONSTRAINT chk_ca_target CHECK ((group_id IS NOT NULL) <> (user_id IS NOT NULL))
);

-- Partial uniqueness rather than a plain UNIQUE, because a NULL never equals a NULL and a plain
-- constraint would happily accept the same team twice.
CREATE UNIQUE INDEX uq_ca_contest_group ON contest_assignments(contest_id, group_id)
    WHERE group_id IS NOT NULL;
CREATE UNIQUE INDEX uq_ca_contest_user  ON contest_assignments(contest_id, user_id)
    WHERE user_id IS NOT NULL;
CREATE INDEX idx_ca_user ON contest_assignments(user_id);

-- The team every existing contest was laid over becomes its first assignment, so one query
-- answers "may this person enter" for old rows and new ones alike.
INSERT INTO contest_assignments (contest_id, group_id)
SELECT contest_id, group_id FROM group_contests WHERE group_id IS NOT NULL;

-- The problems of an event, as CPIntel needs them: order, label and what each is worth.
--
-- The statement, the test data and the verdict stay on the judge. Duplicating those here would
-- create a second source of truth for the one thing the judge is actually authoritative about,
-- and the copy would be wrong the moment someone fixed a test case.
CREATE TABLE contest_problems (
    problem_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contest_id   BIGINT       NOT NULL,
    -- A, B, C… — what the contestant sees, and how a submission names the problem.
    label        VARCHAR(16)  NOT NULL,
    title        VARCHAR(200),
    -- The judge's own problem id, when it differs from the label.
    external_id  VARCHAR(100),
    ordering     INTEGER      DEFAULT 0 NOT NULL,
    -- Points in a contest, marks in an examination. The same number either way.
    points       NUMERIC(10,2),
    created_at   TIMESTAMPTZ  DEFAULT now() NOT NULL,
    CONSTRAINT fk_cp_contest FOREIGN KEY (contest_id) REFERENCES group_contests(contest_id) ON DELETE CASCADE,
    CONSTRAINT uq_cp_contest_label UNIQUE (contest_id, label)
);

-- Everything that happened during an examination, in one append-only log.
--
-- Wider than contest_violations, which records only what the lock observed. This records the
-- ordinary course of an examination as well — entered, problem opened, submitted, verdict — so
-- that an admin reading a candidate's row after the fact sees the session rather than only the
-- accusations in it. The two are kept apart rather than merged because the violation feed is
-- what the standings screen summarises, and burying three focus losses in four hundred
-- problem-opened rows would make it useless.
CREATE TABLE exam_events (
    event_row_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contest_id    BIGINT       NOT NULL,
    user_id       BIGINT       NOT NULL,
    -- Client-generated and stable across retries, so a flaky connection cannot turn one event
    -- into five.
    event_id      VARCHAR(64)  NOT NULL,
    type          VARCHAR(40)  NOT NULL,
    problem_label VARCHAR(16),
    duration_ms   BIGINT,
    detail        VARCHAR(500),
    -- Anything type-specific, as JSON. Read for display only; nothing branches on it.
    metadata      TEXT,
    occurred_at   TIMESTAMPTZ  NOT NULL,
    recorded_at   TIMESTAMPTZ  DEFAULT now() NOT NULL,
    CONSTRAINT fk_ee_contest FOREIGN KEY (contest_id) REFERENCES group_contests(contest_id) ON DELETE CASCADE,
    CONSTRAINT fk_ee_user    FOREIGN KEY (user_id)    REFERENCES users(user_id)             ON DELETE CASCADE,
    CONSTRAINT uq_ee_event   UNIQUE (contest_id, user_id, event_id)
);

CREATE INDEX idx_ee_contest      ON exam_events(contest_id, occurred_at DESC);
CREATE INDEX idx_ee_contest_user ON exam_events(contest_id, user_id, occurred_at DESC);
CREATE INDEX idx_ee_type         ON exam_events(contest_id, type);
-- Retention sweeps delete by age across every event, so the age column needs its own index.
CREATE INDEX idx_ee_recorded     ON exam_events(recorded_at);

CREATE INDEX IF NOT EXISTS idx_gc_kind ON group_contests(kind, lifecycle);
