package com.cpintel.entity;

import jakarta.persistence.*;
import lombok.*;

import java.time.Instant;

/**
 * Something the desktop lock reported during a group contest.
 *
 * Append-only, and deliberately factual rather than accusatory. A focus loss is a focus loss;
 * whether it was a cheat, a notification or someone answering the door is not something the
 * software can know, and the admin screen is written to keep that distinction visible.
 */
@Entity
@Table(name = "contest_violations")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ContestViolation {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "violation_id")
    private Long violationId;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "contest_id", nullable = false)
    private GroupContest contest;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    /**
     * Generated by the reporting client.
     *
     * The desktop app retries a failed report, so without a stable id per event a flaky
     * connection would turn one focus loss into five and make the count meaningless.
     */
    @Column(name = "event_id", nullable = false, length = 64)
    private String eventId;

    @Column(name = "type", nullable = false, length = 40)
    private String type;

    @Column(name = "detail", length = 500)
    private String detail;

    @Column(name = "duration_ms")
    private Long durationMs;

    @Column(name = "occurred_at", nullable = false)
    private Instant occurredAt;

    @Column(name = "reported_at", nullable = false)
    @Builder.Default
    private Instant reportedAt = Instant.now();

    /** What the monitor is able to observe. Nothing here is proof of anything by itself. */
    public enum Type {
        /**
         * The contestant was away from the contest window for longer than the warning
         * threshold. Brief glances are counted on the client but never escalated to here —
         * a feed full of two-second blips would bury the four-minute absence that matters.
         */
        FOCUS_LOST,
        /** Clipboard content that appeared while the window was away, and was discarded. */
        CLIPBOARD_FOREIGN,
        /** Navigation or a window-open the monitor refused. */
        BLOCKED_ACTION,
        /** Sat in a browser, where monitoring is weaker and can simply be closed. */
        LOCKDOWN_UNAVAILABLE,
        /**
         * No longer emitted. It meant the operating system had refused to hand over some
         * keyboard shortcuts, back when the desktop build tried to grab them; that approach
         * was dropped for monitoring instead. Kept so historical rows still read.
         */
        LOCKDOWN_PARTIAL,
        /** Monitoring stopped while the contest was still running. */
        LOCKDOWN_RELEASED
    }
}
