package com.cpintel.entity;

import jakarta.persistence.*;
import lombok.*;

import java.time.Instant;

/**
 * One thing that happened during an examination, for one candidate.
 *
 * <p>Wider than {@link ContestViolation} on purpose. That table holds what the monitor
 * observed, and the standings screen summarises it; this holds the ordinary course of a
 * session as well — entered, problem opened, submitted, verdict received — so that an admin
 * reading a candidate's row afterwards sees what they did, not only what was held against
 * them. Merging the two would bury three focus losses in four hundred problem-opened rows and
 * make the conduct summary useless.
 *
 * <p>Append-only, and factual rather than accusatory: a focus loss is a focus loss, and whether
 * it was a cheat, a notification or someone answering the door is not something software can
 * know. {@link Type#SUSPICIOUS_ACTIVITY} is named for what it is — something worth a human
 * look — rather than as a finding.
 */
@Entity
@Table(name = "exam_events")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ExamEvent {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "event_row_id")
    private Long eventRowId;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "contest_id", nullable = false)
    private GroupContest contest;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    /**
     * Generated by the reporting client and stable across retries.
     *
     * A page that loses its connection mid-examination retries its queue; without this, one
     * focus loss becomes five and every count built on the log becomes a fiction.
     */
    @Column(name = "event_id", nullable = false, length = 64)
    private String eventId;

    @Column(name = "type", nullable = false, length = 40)
    private String type;

    /** The problem this is about, where one applies — A, B, C… */
    @Column(name = "problem_label", length = 16)
    private String problemLabel;

    @Column(name = "duration_ms")
    private Long durationMs;

    @Column(name = "detail", length = 500)
    private String detail;

    /** Anything type-specific, as JSON. Shown; never branched on. */
    @Column(name = "metadata", columnDefinition = "TEXT")
    private String metadata;

    @Column(name = "occurred_at", nullable = false)
    private Instant occurredAt;

    @Column(name = "recorded_at", nullable = false)
    @Builder.Default
    private Instant recordedAt = Instant.now();

    /**
     * What an examination session can produce.
     *
     * The list is closed: an unknown type from a newer or tampered client is dropped rather
     * than stored, because an unreadable row in a log somebody will be judged against is worse
     * than no row at all.
     */
    public enum Type {
        /** The examination's window opened. Recorded once, by the first client to notice. */
        EXAM_STARTED,
        /** This candidate opened the examination. */
        EXAM_ENTERED,
        PROBLEM_OPENED,
        PROBLEM_SUBMITTED,
        SUBMISSION_RESULT,
        FOCUS_LOST,
        FOCUS_REGAINED,
        /** An absence ran past the threshold this examination was configured with. */
        AWAY_THRESHOLD_EXCEEDED,
        /** The candidate left the examination interface without finishing. */
        EXAM_EXITED,
        EXAM_COMPLETED,
        /** Monitoring stopped, or the session was ended from elsewhere. */
        SESSION_TERMINATED,
        /** A desktop restriction fired — a refused navigation, a wiped clipboard. */
        LOCKDOWN_TRIGGERED,
        /** Something worth a human look. Never a finding on its own. */
        SUSPICIOUS_ACTIVITY
    }
}
